#!/bin/sh

set -e

case "$1" in
  configure)
    update-alternatives --install /usr/bin/go go /usr/bin/loongson-golang 5
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "$0: didn't understand being called with \`$1'" 1>&2
    exit 0
    ;;
esac


#DEBHELPER#

exit 0
