#!/bin/sh

set -e

case "$1" in
  remove|upgrade|deconfigure)
    update-alternatives --remove go /usr/bin/loongson-golang
    ;;
  failed-upgrade)
    ;;
  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 0
    ;;
esac

#DEBHELPER#

exit 0
